// data/mockProducts.ts
import { Product } from './product-card';

export const mockProducts: Product[] = [
    {
        id: '1',
        title: 'The High Roller Experience',
        description: '7 days 6 nights - Family',
        imageUrl: 'https://images.pexels.com/photos/28948702/pexels-photo-28948702/free-photo-of-reflection-of-historic-cathedral-in-puddle.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load',
        isFire: true,
        daysAndNights: '7 days 6 nights - Family',
        rating: 5.0,
        price: 17.32,
        currency: 'USD',
    },
    {
        id: '2',
        title: 'Breathtaking View at Sunset',
        description: 'Experience the beauty of nature',
        imageUrl: 'https://images.pexels.com/photos/754079/pexels-photo-754079.jpeg?auto=compress&cs=tinysrgb&w=600',
        isFire: false,
        daysAndNights: 'One evening',
        rating: 4.7,
        price: 30.00,
        currency: 'USD',
    },
    {
        id: '3',
        title: 'Adventure in the Mountains',
        description: 'Full-day hike with family and friends',
        imageUrl: 'https://images.pexels.com/photos/27054224/pexels-photo-27054224/free-photo-of-motorbike-parked-on-hill-on-sea-coast.jpeg?auto=compress&cs=tinysrgb&w=400&lazy=load',
        isFire: false,
        daysAndNights: '1 day',
        rating: 4.5,
        price: 25.00,
        currency: 'USD',
    },
    {
        id: '4',
        title: 'Beach Paradise Getaway',
        description: 'Relax and unwind at the beach',
        imageUrl: 'https://images.pexels.com/photos/8402676/pexels-photo-8402676.jpeg?auto=compress&cs=tinysrgb&w=400&lazy=load',
        isFire: false,
        daysAndNights: '5 days 4 nights',
        rating: 4.8,
        price: 120.00,
        currency: 'USD',
    },
    {
        id: '5',
        title: 'City Lights Night Tour',
        description: 'Discover the bright city by night',
        imageUrl: 'https://images.pexels.com/photos/1995603/pexels-photo-1995603.jpeg?auto=compress&cs=tinysrgb&w=600',
        isFire: false,
        daysAndNights: 'Evening',
        rating: 4.6,
        price: 40.00,
        currency: 'USD',
    },
    {
        id: '6',
        title: 'Historical Landmarks Tour',
        description: 'Explore ancient architecture',
        imageUrl: 'https://images.pexels.com/photos/3647620/pexels-photo-3647620.jpeg?auto=compress&cs=tinysrgb&w=600',
        isFire: false,
        daysAndNights: 'All-day',
        rating: 4.4,
        price: 50.00,
        currency: 'USD',
    },
    {
        id: '7',
        title: 'Guided Wildlife Safari',
        description: 'Experience the wild like never before',
        imageUrl: 'https://images.pexels.com/photos/28999324/pexels-photo-28999324/free-photo-of-vintage-red-tram-on-cobbled-prague-street.jpeg?auto=compress&cs=tinysrgb&w=400&lazy=load',
        isFire: false,
        daysAndNights: 'Full day',
        rating: 4.9,
        price: 75.00,
        currency: 'USD',
    },
    {
        id: '8',
        title: 'Cooking Class with a Chef',
        description: 'Learn cooking from a professional chef',
        imageUrl: 'https://images.pexels.com/photos/5403895/pexels-photo-5403895.jpeg?auto=compress&cs=tinysrgb&w=600',
        isFire: false,
        daysAndNights: 'Evening',
        rating: 4.3,
        price: 80.00,
        currency: 'USD',
    },
    {
        id: '9',
        title: 'Wine Tasting Experience',
        description: 'Enjoy a day of wine tasting',
        imageUrl: 'https://images.pexels.com/photos/29276458/pexels-photo-29276458/free-photo-of-colorful-wooden-houses-in-bergen-norway.jpeg?auto=compress&cs=tinysrgb&w=400&lazy=load',
        isFire: false,
        daysAndNights: '5 hours',
        rating: 4.8,
        price: 60.00,
        currency: 'USD',
    },
    {
        id: '10',
        title: 'Photography Workshop',
        description: 'Enhance your photography skills',
        imageUrl: 'https://images.pexels.com/photos/12116470/pexels-photo-12116470.jpeg?auto=compress&cs=tinysrgb&w=600',
        isFire: false,
        daysAndNights: '2 days',
        rating: 4.7,
        price: 150.00,
        currency: 'USD',
    },
];