import type {Metadata} from "next";
import "./globals.css";
import {Manrope} from "next/font/google";
import {cn} from "@/lib/utils";
import AppLayout from "@/layouts/app-layout";

const manrope = Manrope({
    weight: ["400", "500", "600", "700", "800"],
    subsets: ["latin"],
    display: "swap",
    style: "normal",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body className={cn(manrope.className)}>
                <AppLayout>{children}</AppLayout>
            </body>
        </html>
    );
}
