// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  badge: dynamic(() => import("./Badge")),
  card_background: dynamic(() => import("./CardBackground")),
  carousel: dynamic(() => import("./Carousel")),
  control_carousel: dynamic(() => import("./ControlCarousel")),
  destination: dynamic(() => import("./Destination")),
  filter_section: dynamic(() => import("./FilterSection")),
  heading: dynamic(() => import("./Heading")),
  image_full: dynamic(() => import("./ImageFull")),
  input_form: dynamic(() => import("./InputForm")),
  payment_carousel: dynamic(() => import("./PaymentCarousel")),
  search_section: dynamic(() => import("./SearchSection")),
  sort_section: dynamic(() => import("./SortSection")),
  store_button: dynamic(() => import("./StoreButton")),
  sub_title: dynamic(() => import("./SubTitle")),
  view_more_button: dynamic(() => import("./ViewMoreButton")),
};
